[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[rpc_endpoints]
local = "http://127.0.0.1:8545"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# Gas settings
[profile.default.gas_limit]
gas_limit = 9223372036854775807
gas_price = 20000000000

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Fuzz testing
[fuzz]
runs = 1000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
